### ISSUE TITLE
Connection reset

### ISSUE THREAD

**Issue by andreabono** [crotwell/seisFile#15]
Working with earthworm wave servers I often get a "connection reset" exception.  
Did I forget something? Maybe an earthbeat is needed? Can you please help me?

**Comment by crotwell** [comment]
I expect that the wave server is closing the connection due to inactivity, but I don't run a earthworm wave server any more so I can't test here. I don't know that it has an inactivity timeout on the connection, but it wouldn't surprise me.

Catching the exception, reconnecting and then resending the request is probably the only way to deal with this.
