### ISSUE TITLE
Not Issue but Question

### ISSUE THREAD

**Issue by wjfrelo** [crotwell/seisFile#8]
Good afternoon Dr. Crotwell,

My name is Wyatt Frelot and I am software engineer simply working to better visualize seismic events and correlate Twitter tweets to help provide more context to what is going on  in a visual kind of way.

As apart of my research, I am parsing raw sensor data from Guralp Sensors specifically. I actively use the seisFile Java Library that you created and it works like a charm! But, it leaves me asking a few questions that I am hoping you can shed some light on.

**Assumptions:**

- Guralp Compression Form produces several types of blocks. Among them are two that I primarily see (status and data blocks).
- When Guralp Data Blocks are decompressed, they generate sample points that are measured in volts/microseconds (digital counts)
- To convert from volts/microseconds to nanometers/second would require calibration data.

**Questions:**

- If I have some telemetry data from the status block. How would I convert voltage/microsecond to nanonmeters/second? I was under the impression without the original sensor calibration data...it couldn't be done.

- Is there a default "setting" that could be used? If so, does that very from sensor type to sensor type?

Any insight/documents you could provide/point me to would be very helpful.

Thanks,

Wyatt

**Comment by crotwell** [comment]
Hi

Glad to hear that the seisFile library is useful. Always nice to get a
little positive feedback.

First, I think the digital counts would be simply volts instead of
volts/microsecond.

The conversion to usually meters/sec can be done in 2 ways depending
on how accurate you want it. The first would just use an overall gain
and the second more accurate is to take into account the frequency
dependence of the correction. In either case you need to get external
information from the station metadata. If the data is available from a
datacenter like IRIS, you can get either the overall gain, or the full
response from the FDSN station web service:
http://service.iris.edu/fdsnws/station/1/

There is actually code in seisFile for connecting to this type of web
service and parsing the output, so might be relatively easy to at
least do the overall gain. If your data does not come from stations
that are in a datacenter that provides metadata, then you may be able
to get the nominal response from the NRL:
http://ds.iris.edu/NRL/
but of course you need to know both the sensor and the datalogger as
well as the setting of each of those in order to find the right
response.

If you want to go with the full response and can find a way to
retrieve it, you need to apply it. An example of doing the
deconvolution is here, but it can be tricky to get right as the
spectral division is inherently unstable, so be careful.
https://github.com/crotwell/fissuresUtil/blob/master/src/main/java/edu/sc/seis/fissuresUtil/bag/Transfer.java

Hope this helps.
